### ISSUE TITLE
coupon webucator is no longer available

### ISSUE THREAD

**Issue by anjaniacatus** [DjangoGirls/organizer-manual#118]

**Comment by das-g** [comment]
Is that true, @amakarudze?

If so, I guess that means we should revert #98 & DjangoGirls/djangogirls#665.

**Comment by das-g** [comment]
@anjaniacatus Thank you for the report. Can you give some more details, e.g. how you got to know about the coupon no longer being available?

**Comment by anjaniacatus** [comment]
Hello @das-g,  @amakarudze sent me an email about that this week as we are asking some coupon for the django girls TNR after event :-)

**Comment by das-g** [comment]
> Hello @das-g, @amakarudze sent me an email about that this week as we are asking some coupon for the django girls TNR after event :-)

Thank you for the clarification and also for already filing a pull request (#119) that will remove the references to that coupon!
