### ISSUE TITLE
FAQ Chapter

### ISSUE THREAD

**Issue by williln** [DjangoGirls/organizer-manual#28]
Based on a Slack discussion, we think we need an FAQ chapter for the organizer's manual. Things it could cover: 

- How to respond to criticism about Django Girls 
- Questions that organizers frequently get 

We need your help! Let us know what questions you have, or what questions you've gotten, and (if you can) suggest an answer!

**Comment by williln** [comment]
I'll start: 

Q: What do I do when someone says that DjangoGirls is sexist? 
A: (Help wanted)

**Comment by encukou** [comment]
I was once asking questions like that. This post answered them: https://hynek.me/articles/how-i-stopped-worrying-and-started-loving-pyladies/

**Comment by olasitarska** [comment]
@encukou thanks, that's really helpful!

**Comment by williln** [comment]
From @olasitsrska on Slack: 

- http://jennifermann.ghost.io/minority-groups-in-tech-is-it-just-reverse-sexism/
- http://geekfeminism.wikia.com/wiki/Reverse_sexism

**Comment by williln** [comment]
Q: Isn't Django Girls sexist? 

A: It really isn't, but we can understand why people might feel that way. If you're having the knee-jerk reaction that reaching out specifically to women hurts men, or hurts diversity efforts in other areas, we encourage you to read [How I Stopped Worrying and Started Loving Pyladies](https://hynek.me/articles/how-i-stopped-worrying-and-started-loving-pyladies/) by Hynek Schlawack. One particularly relevant quote is this: 

> Outreach programs don’t divide our community. They incubate people which aren’t comfortable to cope with us from the beginning on and grow our community in the long term.

> It doesn’t really matter whose fault the initial discomfort is. Whether they’re being over-sensitive (hint: [they aren’t](http://therealkatie.net/blog/2012/mar/21/lighten-up/)) or whether we’re a bunch of a**holes (I know you aren’t). The facts are these: if we want underrepresented people to enrich our community, we have to look for pragmatic ways to get them in. Even if the methods don’t seem sound to us on the first sight to us.

> “Yes, but…” discussion don’t help. PyLadies – and similar outreach groups – found a way that works. So be thankful to their organizers for doing this! And again: if you know of a better way, stop sh*tting on their approach and go for it! The world isn’t binary; the more approaches, the more diversity, the better.

Also, not all Django Girls events are exclusive to women. Our organizer's manual encourages organizers to use our materials to put on workshops for women *and* for mixed-gender groups. We've also open-sourced all of our content, so if you like our tutorial but don't want to put on a Django Girls event with it, feel free to fork it, credit us for the content, but rebrand it into something that works for your goals.  

We don't want to get men *out* of programming; we just want to bring more women *in*. There are already a lot of other bootcamps, workshops, meetups, and groups that are "mixed gender," but are really mostly men. We've found that by limiting our workshop to a majority of women participants, women are more comfortable signing up, asking questions, getting involved, and even staying involved later on. And that's a good thing!

**Comment by williln** [comment]
@encukou Thank you for that essay. I'd seen it before but forgot about it! 

@olasitarska and everyone else, what do you think of this as a possible "answer" to the question of sexism? 

Also, next question: 

**Q: I'm an organizer, and I'm being accused of being sexist/breaking discrimination laws. What should I do?**

**Comment by tricoder42** [comment]
@williln I like it, thank you

**Comment by bmispelon** [comment]
I think it's great, I'm in favor of adding this right now and expanding the FAQ as we go.

You feel like making a pull request? :shipit:

**Comment by williln** [comment]
@bmispelon :music note: Do you wanna make a PR? :smile:

**Comment by williln** [comment]
Sure! I can work on that this morning.

**Comment by bmispelon** [comment]
:musical_note: :snowman: :question:
