### ISSUE TITLE
Organize a doc sprint

### ISSUE THREAD

**Issue by patjouk** [DjangoGirls/organizer-manual#38]
Another issue for @thatdocslady!
The idea will be to add a section in the organizer manual on how to make a doc sprint after an event.

**Comment by souravsingh** [comment]
Is the issue still open?

**Comment by olasitarska** [comment]
Yes :)

**Comment by thatdocslady** [comment]
Yeah, sorry about the delay - it's hard to track issues that aren't
directly assigned to me, and this keep slipping...

Is there any way to give me enough karma so that you can assign issues to
me but no more than needed?

**Comment by olasitarska** [comment]
@thatdocslady I'm trying something, could you accept the invite I just sent you?

**Comment by olasitarska** [comment]
cool, so a solution I found for assigning someone to an issue without giving them commit rights is to add them to a new team in Django Girls organization on Github called @DjangoGirls/assigned. This gives only read rights, but still allows for assigning. WIN!

**Comment by thatdocslady** [comment]
Oh great, thanks! I love the new GH teams :)

**Comment by olasitarska** [comment]
I'm gonna close this :)
