### ISSUE TITLE
Last minute shopping list

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/organizer-manual#46]
I'm thinking it'd be nice to have a last minute shopping list / checklist of things that are really useful but you might not think to bring. I had a crazy last minute rush around a supermarket and I think that happened last time too (and I still forgot some of these :) 

Off the top of my head:

* blu-tack
* scissors
* sticky tape
* bin bags
* string
* spare paper and pens
* tissues / toilet roll
* sanitary pads

**Comment by aniav** [comment]
This is a great idea! :)
