### ISSUE TITLE
Warn about setting up correct sharing settings on attendee forms results

### ISSUE THREAD

**Issue by bmispelon** [DjangoGirls/organizer-manual#6]
The manual should tell the organizer to make sure that the sharing settings on attendee forms results are set so that they can't be accessed publicly.

The form result can contain sensitive data like personal phone numbers so it should not be viewable by anyone outside the organizing team.

**Comment by williln** [comment]
Can this be closed since we now have the applications on the website? (Also hooray for having apps on the website!)

**Comment by olasitarska** [comment]
Perfection :heart: (I wanted to use :django_heart: here :cry:)
