### ISSUE TITLE
Do a chapter summarizing the most important content in the manual

### ISSUE THREAD

**Issue by patjouk** [DjangoGirls/organizer-manual#78]
The organizers' manual is getting bigger and bigger and it would be nice to have a chapter summarizing what is in each chapter of the manual.

**Comment by thatdocslady** [comment]
Reviewing the guide again, I'm actually thinking it might be more useful to update the existing "step by step" schedule checklist to reflect more accurately the content in the guide (fix links and phrasing to indicate which chapters should be read when). 

I'd also add a "before you start" section where we can include links to "homework" to do before you begin the actual process. WDYT @patjouk ?
