### ISSUE TITLE
Translate Manual to Spanish

### ISSUE THREAD

**Issue by ma0c** [DjangoGirls/organizer-manual#92]
At [Python-Cali](https://www.meetup.com/es/Python-Cali/) we're working to have a Django Girls Event in our city, and we're already made a request to Django Girls to have an Event in our city. I was checking online resources and notice that this organizer manual is only available in English, so I ask if you're open to translation for this manual.

Greets from Colombia

**Comment by magul** [comment]
Hi @ma0c, I don't know it there's strict policy here, but from my point of view it looks that our first priority is to translate tutorial and maybe tutorial extentions.

As I see, You already found a Crowdin project for tutorial (Spanish version has only 76% coverage there), we don't have project for extentions yet and really don't know if there's a manpower to translate and maintain it.

**Comment by ma0c** [comment]
I've already made an effort to translate extensions at [this pull request](https://github.com/DjangoGirls/tutorial-extensions/pull/98), but sure, Official Tutorial has priority, going to translate remaining sentences at crowdin
